package com.github.thundax.architecture;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.github.thundax.common.test.architecture.AbstractArchitectureTest;
import com.github.thundax.common.test.architecture.ModelAnnotationArchitectureRuleSupport;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.domain.JavaField;
import org.junit.Test;

public class DataObjectAnnotationArchitectureTest extends AbstractArchitectureTest {

    private static final String BASE_PACKAGE = "com.github.thundax.modules";
    private static final String DEFAULT_ENCRYPT_TYPE_HANDLER =
            "com.github.thundax.common.persistence.typehandler.DefaultEncryptTypeHandler";

    private static final String[] NON_AUTO_ID_DATA_OBJECTS = {
        "com.github.thundax.modules.assist.persistence.dataobject.AsyncTaskDO",
        "com.github.thundax.modules.auth.persistence.dataobject.AccessTokenDO",
        "com.github.thundax.modules.auth.persistence.dataobject.LoginFormDO",
        "com.github.thundax.modules.storage.persistence.dataobject.StoredObjectReferenceDO",
        "com.github.thundax.modules.sys.persistence.dataobject.MenuRoleDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserRoleDO"
    };
    private static final String[] SNOWFLAKE_ID_DATA_OBJECTS = {
        "com.github.thundax.modules.auth.persistence.dataobject.AuthSessionDO",
        "com.github.thundax.modules.auth.persistence.dataobject.OAuthAccessTokenDO",
        "com.github.thundax.modules.auth.persistence.dataobject.OAuthAuthorizationDO",
        "com.github.thundax.modules.auth.persistence.dataobject.OAuthClientDO",
        "com.github.thundax.modules.auth.persistence.dataobject.OAuthRefreshTokenDO",
        "com.github.thundax.modules.auth.persistence.dataobject.PrincipalCredentialDO",
        "com.github.thundax.modules.auth.persistence.dataobject.PrincipalIdentityDO",
        "com.github.thundax.modules.auth.persistence.dataobject.MemberAccessTokenDO",
        "com.github.thundax.modules.auth.persistence.dataobject.MemberAuthSessionDO",
        "com.github.thundax.modules.member.persistence.dataobject.MemberCredentialDO",
        "com.github.thundax.modules.member.persistence.dataobject.MemberDO",
        "com.github.thundax.modules.member.persistence.dataobject.MemberIdentityDO",
        "com.github.thundax.modules.auth.persistence.dataobject.MemberRefreshTokenDO",
        "com.github.thundax.modules.storage.persistence.dataobject.MultipartUploadPartDO",
        "com.github.thundax.modules.storage.persistence.dataobject.MultipartUploadSessionDO",
        "com.github.thundax.modules.storage.persistence.dataobject.StoredObjectDO",
        "com.github.thundax.modules.sys.persistence.dataobject.DepartmentDO",
        "com.github.thundax.modules.sys.persistence.dataobject.DictDO",
        "com.github.thundax.modules.sys.persistence.dataobject.LogDO",
        "com.github.thundax.modules.sys.persistence.dataobject.MenuDO",
        "com.github.thundax.modules.sys.persistence.dataobject.RoleDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserCredentialDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserIdentityDO"
    };
    private static final String[] LEGACY_TABLE_NAME_DATA_OBJECTS = {};

    @Test
    public void shouldEnforceDatabaseDataObjectClassAnnotations() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        ModelAnnotationArchitectureRuleSupport.dataObjectClassAnnotationsRequired(
                        BASE_PACKAGE,
                        "com.github.thundax.modules.assist.persistence.dataobject.AsyncTaskDO",
                        "com.github.thundax.modules.auth.persistence.dataobject.AccessTokenDO",
                        "com.github.thundax.modules.auth.persistence.dataobject.LoginFormDO")
                .check(classes);
    }

    @Test
    public void shouldEnforceIndependentDataObjectAutoGeneratedId() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass) || isNonAutoIdDataObject(javaClass)) {
                continue;
            }
            if (isSnowflakeIdDataObject(javaClass)) {
                assertTableId(javaClass, "id", "", IdType.INPUT, Long.class);
            } else {
                fail(javaClass.getFullName() + " must be registered as snowflake or non-auto id data object");
            }
        }
    }

    @Test
    public void shouldUseSourceNamedKeyForSharedPrimaryKeyDataObjects() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        JavaClass storageBusinessDO = classByName(
                classes, "com.github.thundax.modules.storage.persistence.dataobject.StoredObjectReferenceDO");
        assertFalse(
                storageBusinessDO.getFullName() + " must not declare id field",
                storageBusinessDO.tryGetField("id").isPresent());
        JavaField fileIdField = storageBusinessDO.getField("fileId");
        assertEquals(
                storageBusinessDO.getFullName() + ".fileId must be Long",
                Long.class.getName(),
                fileIdField.getRawType().getFullName());
        assertFalse(
                storageBusinessDO.getFullName() + ".fileId must not be single-column TableId",
                fileIdField.isAnnotatedWith(TableId.class));
    }

    @Test
    public void shouldUseDatabaseAuditFieldNamesForDataObjects() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass)) {
                continue;
            }
            assertFalse(
                    javaClass.getFullName() + " must not declare createUserId field",
                    javaClass.tryGetField("createUserId").isPresent());
            assertFalse(
                    javaClass.getFullName() + " must not declare updateUserId field",
                    javaClass.tryGetField("updateUserId").isPresent());
        }
    }

    @Test
    public void shouldUseAllowedTableNamePrefixForDataObjects() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass) || !javaClass.isAnnotatedWith(TableName.class)) {
                continue;
            }
            String tableName = javaClass.getAnnotationOfType(TableName.class).value();
            if (isLegacyTableNameDataObject(javaClass)) {
                assertStartsWith(javaClass, tableName, "tb_");
            } else {
                assertAllowedTablePrefix(javaClass, tableName);
            }
        }
    }

    @Test
    public void shouldKeepDataObjectsAlignedWithDatabaseColumns() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass)) {
                continue;
            }
            assertFalse(
                    javaClass.getFullName() + " must not declare delFlag field",
                    javaClass.tryGetField("delFlag").isPresent());
            for (JavaField field : javaClass.getFields()) {
                if (!field.isAnnotatedWith(TableField.class)) {
                    continue;
                }
                TableField tableField = field.getAnnotationOfType(TableField.class);
                assertEquals(
                        field.getFullName() + " TableField is only allowed for typeHandler", "", tableField.value());
                assertEquals(
                        field.getFullName() + " TableField must map to a real database column",
                        true,
                        tableField.exist());
                assertEquals(
                        field.getFullName() + " only DefaultEncryptTypeHandler may use TableField",
                        DEFAULT_ENCRYPT_TYPE_HANDLER,
                        tableField.typeHandler().getName());
            }
        }
    }

    private JavaClass classByName(JavaClasses classes, String className) {
        for (JavaClass javaClass : classes) {
            if (javaClass.getFullName().equals(className)) {
                return javaClass;
            }
        }
        fail("Missing imported class: " + className);
        return null;
    }

    private void assertTableId(
            JavaClass javaClass, String fieldName, String columnName, IdType idType, Class<?> idClass) {
        JavaField field = javaClass.getField(fieldName);
        assertEquals(
                javaClass.getFullName() + "." + fieldName + " must be " + idClass.getSimpleName(),
                idClass.getName(),
                field.getRawType().getFullName());
        TableId tableId = field.getAnnotationOfType(TableId.class);
        assertEquals(javaClass.getFullName() + "." + fieldName + " TableId value", columnName, tableId.value());
        assertEquals(javaClass.getFullName() + "." + fieldName + " TableId type", idType, tableId.type());
    }

    private boolean isDataObjectClass(JavaClass javaClass) {
        return javaClass.getPackageName().startsWith(BASE_PACKAGE + ".")
                && javaClass.getPackageName().contains(".persistence.dataobject")
                && (javaClass.getSimpleName().endsWith("DO")
                        || javaClass.getSimpleName().endsWith("DataObject"));
    }

    private boolean isNonAutoIdDataObject(JavaClass javaClass) {
        for (String className : NON_AUTO_ID_DATA_OBJECTS) {
            if (javaClass.getFullName().equals(className)) {
                return true;
            }
        }
        return false;
    }

    private boolean isSnowflakeIdDataObject(JavaClass javaClass) {
        for (String className : SNOWFLAKE_ID_DATA_OBJECTS) {
            if (javaClass.getFullName().equals(className)) {
                return true;
            }
        }
        return false;
    }

    private boolean isLegacyTableNameDataObject(JavaClass javaClass) {
        for (String className : LEGACY_TABLE_NAME_DATA_OBJECTS) {
            if (javaClass.getFullName().equals(className)) {
                return true;
            }
        }
        return false;
    }

    private void assertAllowedTablePrefix(JavaClass javaClass, String tableName) {
        if (tableName.startsWith("sys_")
                || tableName.startsWith("auth_")
                || tableName.startsWith("assist_")
                || tableName.startsWith("member_")) {
            return;
        }
        fail(javaClass.getFullName() + " uses unsupported table prefix: " + tableName);
    }

    private void assertStartsWith(JavaClass javaClass, String tableName, String prefix) {
        if (tableName.startsWith(prefix)) {
            return;
        }
        fail(javaClass.getFullName() + " legacy table name must start with " + prefix + ": " + tableName);
    }
}
