package com.github.thundax.architecture;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.fail;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.github.thundax.common.test.architecture.AbstractArchitectureTest;
import com.github.thundax.common.test.architecture.ModelAnnotationArchitectureRuleSupport;
import com.tngtech.archunit.core.domain.JavaClass;
import com.tngtech.archunit.core.domain.JavaClasses;
import com.tngtech.archunit.core.domain.JavaField;
import org.junit.Test;

public class DataObjectAnnotationArchitectureTest extends AbstractArchitectureTest {

    private static final String BASE_PACKAGE = "com.github.thundax.modules";
    private static final String DEFAULT_ENCRYPT_TYPE_HANDLER =
            "com.github.thundax.common.persistence.typehandler.DefaultEncryptTypeHandler";

    private static final String[] NON_AUTO_ID_DATA_OBJECTS = {
        "com.github.thundax.modules.assist.persistence.dataobject.AsyncTaskDO",
        "com.github.thundax.modules.assist.persistence.dataobject.SignatureDO",
        "com.github.thundax.modules.auth.persistence.dataobject.AccessTokenDO",
        "com.github.thundax.modules.auth.persistence.dataobject.LoginFormDO",
        "com.github.thundax.modules.storage.persistence.dataobject.StorageBusinessDO",
        "com.github.thundax.modules.sys.persistence.dataobject.MenuRoleDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserEncryptDO",
        "com.github.thundax.modules.sys.persistence.dataobject.UserRoleDO"
    };

    @Test
    public void shouldEnforceDatabaseDataObjectClassAnnotations() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        ModelAnnotationArchitectureRuleSupport.dataObjectClassAnnotationsRequired(
                        BASE_PACKAGE,
                        "com.github.thundax.modules.assist.persistence.dataobject.AsyncTaskDO",
                        "com.github.thundax.modules.auth.persistence.dataobject.AccessTokenDO",
                        "com.github.thundax.modules.auth.persistence.dataobject.LoginFormDO")
                .check(classes);
    }

    @Test
    public void shouldEnforceIndependentDataObjectAutoGeneratedStringId() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass) || isNonAutoIdDataObject(javaClass)) {
                continue;
            }
            assertTableId(javaClass, "id", "", IdType.ASSIGN_UUID);
        }
    }

    @Test
    public void shouldUseSourceNamedKeyForSharedPrimaryKeyDataObjects() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        JavaClass userEncryptDO =
                classByName(classes, "com.github.thundax.modules.sys.persistence.dataobject.UserEncryptDO");
        assertFalse(
                userEncryptDO.getFullName() + " must not declare id field",
                userEncryptDO.tryGetField("id").isPresent());
        assertTableId(userEncryptDO, "userId", "id", IdType.INPUT);

        JavaClass storageBusinessDO =
                classByName(classes, "com.github.thundax.modules.storage.persistence.dataobject.StorageBusinessDO");
        assertFalse(
                storageBusinessDO.getFullName() + " must not declare id field",
                storageBusinessDO.tryGetField("id").isPresent());
        assertTableId(storageBusinessDO, "storageId", "file_id", IdType.INPUT);
    }

    @Test
    public void shouldUseDatabaseAuditFieldNamesForDataObjects() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass)) {
                continue;
            }
            assertFalse(
                    javaClass.getFullName() + " must not declare createUserId field",
                    javaClass.tryGetField("createUserId").isPresent());
            assertFalse(
                    javaClass.getFullName() + " must not declare updateUserId field",
                    javaClass.tryGetField("updateUserId").isPresent());
        }
    }

    @Test
    public void shouldKeepDataObjectsAlignedWithDatabaseColumns() {
        JavaClasses classes = importPackages(BASE_PACKAGE);

        for (JavaClass javaClass : classes) {
            if (!isDataObjectClass(javaClass)) {
                continue;
            }
            assertFalse(
                    javaClass.getFullName() + " must not declare delFlag field",
                    javaClass.tryGetField("delFlag").isPresent());
            for (JavaField field : javaClass.getFields()) {
                if (!field.isAnnotatedWith(TableField.class)) {
                    continue;
                }
                TableField tableField = field.getAnnotationOfType(TableField.class);
                assertEquals(
                        field.getFullName() + " TableField is only allowed for typeHandler", "", tableField.value());
                assertEquals(
                        field.getFullName() + " TableField must map to a real database column",
                        true,
                        tableField.exist());
                assertEquals(
                        field.getFullName() + " only DefaultEncryptTypeHandler may use TableField",
                        DEFAULT_ENCRYPT_TYPE_HANDLER,
                        tableField.typeHandler().getName());
            }
        }
    }

    private JavaClass classByName(JavaClasses classes, String className) {
        for (JavaClass javaClass : classes) {
            if (javaClass.getFullName().equals(className)) {
                return javaClass;
            }
        }
        fail("Missing imported class: " + className);
        return null;
    }

    private void assertTableId(JavaClass javaClass, String fieldName, String columnName, IdType idType) {
        JavaField field = javaClass.getField(fieldName);
        assertEquals(
                javaClass.getFullName() + "." + fieldName + " must be String",
                String.class.getName(),
                field.getRawType().getFullName());
        TableId tableId = field.getAnnotationOfType(TableId.class);
        assertEquals(javaClass.getFullName() + "." + fieldName + " TableId value", columnName, tableId.value());
        assertEquals(javaClass.getFullName() + "." + fieldName + " TableId type", idType, tableId.type());
    }

    private boolean isDataObjectClass(JavaClass javaClass) {
        return javaClass.getPackageName().startsWith(BASE_PACKAGE + ".")
                && javaClass.getPackageName().contains(".persistence.dataobject")
                && (javaClass.getSimpleName().endsWith("DO")
                        || javaClass.getSimpleName().endsWith("DataObject"));
    }

    private boolean isNonAutoIdDataObject(JavaClass javaClass) {
        for (String className : NON_AUTO_ID_DATA_OBJECTS) {
            if (javaClass.getFullName().equals(className)) {
                return true;
            }
        }
        return false;
    }
}
