server {
    listen 80;
    server_name _;

    location = /admin {
        return 301 /admin/;
    }

    location ^~ /admin/ {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

    location ^~ /admin-api/ {
        proxy_pass http://sandwish-admin-api:8080/admin-api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ^~ /front-api/ {
        proxy_pass http://sandwish-front-api:8080/front-api/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html/front;
        try_files $uri $uri/ /index.html;
    }
}
