SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `audit_meta` (
    `id` bigint NOT NULL,
    `object_type` varchar(64) NOT NULL,
    `object_id` varchar(128) NOT NULL,
    `version` bigint NOT NULL,
    `last_log_id` bigint NOT NULL,
    `last_action` varchar(32) NOT NULL,
    `last_operator_type` varchar(32) NOT NULL,
    `last_operator_id` varchar(64) DEFAULT NULL,
    `last_operator_name` varchar(128) DEFAULT NULL,
    `last_operated_at` datetime(3) NOT NULL,
    `created_log_id` bigint NOT NULL,
    `created_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_audit_meta_object` (`object_type`, `object_id`),
    KEY `idx_audit_meta_last_operated` (`last_operated_at`),
    KEY `idx_audit_meta_last_operator` (`last_operator_type`, `last_operator_id`, `last_operated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审计元数据表';

CREATE TABLE IF NOT EXISTS `audit_log` (
    `id` bigint NOT NULL,
    `meta_id` bigint NOT NULL,
    `object_type` varchar(64) NOT NULL,
    `object_id` varchar(128) NOT NULL,
    `version` bigint NOT NULL,
    `previous_version` bigint NOT NULL,
    `action` varchar(32) NOT NULL,
    `idempotency_key` varchar(255) NOT NULL,
    `operator_type` varchar(32) NOT NULL,
    `operator_id` varchar(64) DEFAULT NULL,
    `operator_name` varchar(128) DEFAULT NULL,
    `source` varchar(32) NOT NULL,
    `request_id` varchar(128) DEFAULT NULL,
    `trace_id` varchar(128) DEFAULT NULL,
    `remote_addr` varchar(64) DEFAULT NULL,
    `summary` varchar(512) DEFAULT NULL,
    `snapshot_schema_version` int NOT NULL,
    `before_snapshot` longtext DEFAULT NULL,
    `after_snapshot` longtext DEFAULT NULL,
    `changed_fields` longtext DEFAULT NULL,
    `occurred_at` datetime(3) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_audit_log_idempotency` (`idempotency_key`),
    KEY `idx_audit_log_object` (`object_type`, `object_id`, `occurred_at`),
    KEY `idx_audit_log_meta_version` (`meta_id`, `version`),
    KEY `idx_audit_log_operator` (`operator_type`, `operator_id`, `occurred_at`),
    KEY `idx_audit_log_action` (`action`, `occurred_at`),
    KEY `idx_audit_log_request` (`request_id`),
    KEY `idx_audit_log_trace` (`trace_id`),
    KEY `idx_audit_log_occurred` (`occurred_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审计日志表';
