CREATE TABLE IF NOT EXISTS `auth_session` (
    `id` bigint NOT NULL,
    `session_id` varchar(64) NOT NULL,
    `token` varchar(255) NOT NULL,
    `user_id` bigint NOT NULL,
    `identity_id` bigint NOT NULL,
    `identity_type` varchar(16) NOT NULL,
    `login_type` varchar(16) NOT NULL,
    `status` varchar(16) NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `last_access_time` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `logout_at` datetime(3) DEFAULT NULL,
    `invalidate_reason` varchar(128) DEFAULT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_session_session_id` (`session_id`),
    UNIQUE KEY `uk_auth_session_token` (`token`),
    KEY `idx_auth_session_user_status` (`user_id`, `status`),
    KEY `idx_auth_session_identity` (`identity_id`, `identity_type`),
    KEY `idx_auth_session_expire` (`status`, `expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台认证会话审计表';

CREATE TABLE IF NOT EXISTS `member_auth_session` (
    `id` bigint NOT NULL,
    `session_id` varchar(64) NOT NULL,
    `member_id` bigint NOT NULL,
    `identity_id` bigint DEFAULT NULL,
    `identity_type` varchar(16) DEFAULT NULL,
    `login_type` varchar(32) DEFAULT NULL,
    `status` varchar(16) NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `last_access_time` datetime(3) DEFAULT NULL,
    `expire_at` datetime(3) DEFAULT NULL,
    `logout_at` datetime(3) DEFAULT NULL,
    `invalidate_reason` varchar(255) DEFAULT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_member_auth_session_session` (`session_id`),
    KEY `idx_member_auth_session_member` (`member_id`, `status`),
    KEY `idx_member_auth_session_status` (`status`, `last_access_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='前台会员认证会话审计表';

CREATE TABLE IF NOT EXISTS `member_access_token` (
    `id` bigint NOT NULL,
    `token_id` varchar(64) NOT NULL,
    `token_hash` varchar(128) NOT NULL,
    `session_id` varchar(64) NOT NULL,
    `member_id` bigint NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `status` varchar(16) NOT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_member_access_token_id` (`token_id`),
    UNIQUE KEY `uk_member_access_token_hash` (`token_hash`),
    KEY `idx_member_access_token_member` (`member_id`, `status`),
    KEY `idx_member_access_token_session` (`session_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='前台会员访问令牌表';

CREATE TABLE IF NOT EXISTS `member_refresh_token` (
    `id` bigint NOT NULL,
    `token_id` varchar(64) NOT NULL,
    `token_hash` varchar(128) NOT NULL,
    `access_token_id` varchar(64) NOT NULL,
    `session_id` varchar(64) NOT NULL,
    `member_id` bigint NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `status` varchar(16) NOT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_member_refresh_token_id` (`token_id`),
    UNIQUE KEY `uk_member_refresh_token_hash` (`token_hash`),
    KEY `idx_member_refresh_token_member` (`member_id`, `status`),
    KEY `idx_member_refresh_token_session` (`session_id`, `status`),
    KEY `idx_member_refresh_token_access` (`access_token_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='前台会员刷新令牌表';

CREATE TABLE IF NOT EXISTS `auth_oauth_client` (
    `id` bigint NOT NULL,
    `client_id` varchar(64) NOT NULL,
    `client_secret_hash` varchar(255) NOT NULL,
    `client_name` varchar(128) NOT NULL,
    `client_type` varchar(32) NOT NULL,
    `grant_types` text NOT NULL,
    `scopes` text NOT NULL,
    `redirect_uris` text NOT NULL,
    `access_token_ttl_seconds` bigint NOT NULL,
    `refresh_token_ttl_seconds` bigint NOT NULL,
    `status` varchar(16) NOT NULL,
    `contact` varchar(128) DEFAULT NULL,
    `remark` varchar(255) DEFAULT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_oauth_client_client_id` (`client_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth2客户端表';

CREATE TABLE IF NOT EXISTS `auth_oauth_authorization` (
    `id` bigint NOT NULL,
    `authorization_code` varchar(128) NOT NULL,
    `client_id` varchar(64) NOT NULL,
    `user_id` bigint NOT NULL,
    `redirect_uri` varchar(512) NOT NULL,
    `scopes` text NOT NULL,
    `state` varchar(255) DEFAULT NULL,
    `code_challenge` varchar(128) DEFAULT NULL,
    `code_challenge_method` varchar(16) DEFAULT NULL,
    `issued_at` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `used` tinyint(1) NOT NULL DEFAULT 0,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_oauth_authorization_code` (`authorization_code`),
    KEY `idx_auth_oauth_authorization_client_user` (`client_id`, `user_id`, `expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth2授权码表';

CREATE TABLE IF NOT EXISTS `auth_oauth_access_token` (
    `id` bigint NOT NULL,
    `token_id` varchar(64) NOT NULL,
    `token_hash` varchar(255) NOT NULL,
    `client_id` varchar(64) NOT NULL,
    `user_id` bigint NOT NULL,
    `scopes` text NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `status` varchar(16) NOT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_oauth_access_token_id` (`token_id`),
    UNIQUE KEY `uk_auth_oauth_access_token_hash` (`token_hash`),
    KEY `idx_auth_oauth_access_token_client_user` (`client_id`, `user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth2访问令牌表';

CREATE TABLE IF NOT EXISTS `auth_oauth_refresh_token` (
    `id` bigint NOT NULL,
    `token_id` varchar(64) NOT NULL,
    `token_hash` varchar(255) NOT NULL,
    `access_token_id` varchar(64) NOT NULL,
    `client_id` varchar(64) NOT NULL,
    `user_id` bigint NOT NULL,
    `issued_at` datetime(3) NOT NULL,
    `expire_at` datetime(3) NOT NULL,
    `status` varchar(16) NOT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_auth_oauth_refresh_token_id` (`token_id`),
    UNIQUE KEY `uk_auth_oauth_refresh_token_hash` (`token_hash`),
    KEY `idx_auth_oauth_refresh_token_client_user` (`client_id`, `user_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='OAuth2刷新令牌表';
