CREATE TABLE IF NOT EXISTS `member_member` (
    `id` varchar(64) NOT NULL,
    `login_name` varchar(128) NOT NULL,
    `login_pass` varchar(255) DEFAULT NULL,
    `email` varchar(512) DEFAULT NULL,
    `name` varchar(128) DEFAULT NULL,
    `gender` varchar(16) DEFAULT NULL,
    `mobile` varchar(512) DEFAULT NULL,
    `address` varchar(512) DEFAULT NULL,
    `zipcode` varchar(32) DEFAULT NULL,
    `enable_flag` varchar(32) NOT NULL DEFAULT 'ENABLED',
    `register_ip` varchar(64) DEFAULT NULL,
    `register_date` datetime(3) DEFAULT NULL,
    `last_login_ip` varchar(64) DEFAULT NULL,
    `last_login_date` datetime(3) DEFAULT NULL,
    `ywtb_id` varchar(128) DEFAULT NULL,
    `login_count` int NOT NULL DEFAULT 0,
    `priority` int NOT NULL DEFAULT 0,
    `remarks` varchar(500) DEFAULT NULL,
    `create_date` datetime(3) NOT NULL,
    `create_by` varchar(64) DEFAULT NULL,
    `update_date` datetime(3) DEFAULT NULL,
    `update_by` varchar(64) DEFAULT NULL,
    `del_flag` char(1) NOT NULL DEFAULT '0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_member_member_login_name` (`login_name`),
    UNIQUE KEY `uk_member_member_ywtb_id` (`ywtb_id`),
    KEY `idx_member_member_status` (`enable_flag`, `priority`, `create_date`),
    KEY `idx_member_member_email` (`email`),
    KEY `idx_member_member_mobile` (`mobile`),
    KEY `idx_member_member_del_flag` (`del_flag`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
