SET NAMES utf8mb4;

-- API KEY / API SECRET are generated by OpenClientService.
-- Seed OpenClients are for management UI and permission data verification only.
-- For Open API call debugging, reset secret through the management API and keep the plaintext outside git.

DELETE FROM `open_client_permission`
WHERE `client_id` IN (
    930000000000000001,
    930000000000000002
);

DELETE FROM `open_client`
WHERE `id` IN (
    930000000000000001,
    930000000000000002
);

INSERT INTO `open_client` (`id`, `name`, `status`, `ip_whitelist`, `expired_at`, `remarks`)
VALUES
    (
        930000000000000001,
        'Submission Sandbox Client',
        'ENABLED',
        '["127.0.0.1","10.0.0.0/24"]',
        NULL,
        '联调样例：通过重置 secret 获取一次性明文，不在备注保存密钥。'
    ),
    (
        930000000000000002,
        'Disabled Demo Client',
        'DISABLED',
        '[]',
        NULL,
        '禁用样例：用于验证 OpenClient 状态过滤和不可调用状态。'
    );

INSERT INTO `open_client_permission` (`id`, `client_id`, `permission`)
VALUES
    (
        930000000000001001,
        930000000000000001,
        'submission:submission:create'
    ),
    (
        930000000000001002,
        930000000000000001,
        'submission:submission:image:upload'
    ),
    (
        930000000000001003,
        930000000000000002,
        'submission:submission:create'
    );
