server:
  port: 20009
  servlet:
    context-path: /putuo-interaction-admin-api
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: putuo-interaction-admin-api

  main:
    bannerMode: "off"

  jmx:
    default-domain: putuo-interaction-admin-api

  mvc:
    throw-exception-if-no-handler-found: true

  thymeleaf:
    enabled: false

  resources:
    add-mappings: false

  messages:
    basename: i18n/messages

  servlet:
    multipart:
      max-file-size: 20971520
      max-request-size: 20971520

  profiles:
    active: vastbase-dev

shiro:
  loginUrl: /admin/login
  successUrl: /admin/index
  sessionManager:
    sessionIdUrlRewritingEnabled: false
    sessionIdCookieEnabled: true
    cookie:
      name: vltava.sid

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: true
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 10000
  remote:
    default:
      type: redis.lettuce
      uri: ${SANDWISH_REDIS_URI:redis://127.0.0.1:6379/0}
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java

logging:
  config: classpath:config/logback-spring.xml
  level:
    com.wdit: INFO

swagger:
  base-package: com.github.thundax.modules
  title: 沃尔塔瓦服务接口
  description: 沃尔塔瓦服务相关接口
