brokerClusterName=DefaultCluster
brokerName=sandwish-it-broker
brokerId=0
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

brokerIP1=127.0.0.1
listenPort=20911
haListenPort=20912

autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true

storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
